<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-01 at 06:25:35.
 */
class SearchEngineTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var SearchEngine
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new SearchEngine;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers SearchEngine::performSearch
	 * @todo   Implement testPerformSearch().
	 */
	public function testPerformSearch() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
